[
    {
        "accuracy": 30,
        "category": "物理",
        "cname": "剪刀断头台",
        "ename": "Guillotine",
        "id": 12,
        "jname": "ハサミギロチン",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "剑舞",
        "ename": "Swords Dance",
        "id": 14,
        "jname": "つるぎのまい",
        "power": null,
        "pp": 20,
        "tm": 75,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "旋风",
        "ename": "Whirlwind",
        "id": 18,
        "jname": "ふきとばし",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "飞沙脚",
        "ename": "Sand Attack",
        "id": 28,
        "jname": "すなかけ",
        "power": null,
        "pp": 15,
        "type": "Ground"
    },
    {
        "accuracy": 30,
        "category": "物理",
        "cname": "独角钻",
        "ename": "Horn Drill",
        "id": 32,
        "jname": "つのドリル",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "摇尾巴",
        "ename": "Tail Whip",
        "id": 39,
        "jname": "しっぽをふる",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "瞪眼",
        "ename": "Leer",
        "id": 43,
        "jname": "にらみつける",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "嚎叫",
        "ename": "Growl",
        "id": 45,
        "jname": "なきごえ",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "吼叫",
        "ename": "Roar",
        "id": 46,
        "jname": "ほえる",
        "power": null,
        "pp": 20,
        "tm": 5,
        "type": "Normal"
    },
    {
        "accuracy": 55,
        "category": "变化",
        "cname": "唱歌",
        "ename": "Sing",
        "id": 47,
        "jname": "うたう",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": 55,
        "category": "变化",
        "cname": "超音波",
        "ename": "Supersonic",
        "id": 48,
        "jname": "ちょうおんぱ",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 90,
        "category": "特殊",
        "cname": "音爆",
        "ename": "Sonic Boom",
        "id": 49,
        "jname": "ソニックブーム",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "石化功",
        "ename": "Disable",
        "id": 50,
        "jname": "かなしばり",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "白雾",
        "ename": "Mist",
        "id": 54,
        "jname": "しろいきり",
        "power": null,
        "pp": 30,
        "type": "Ice"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "下踢",
        "ename": "Low Kick",
        "id": 67,
        "jname": "けたぐり",
        "power": null,
        "pp": 20,
        "type": "Fighting"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "返拳",
        "ename": "Counter",
        "id": 68,
        "jname": "カウンター",
        "power": null,
        "pp": 20,
        "type": "Fighting"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "地球上投",
        "ename": "Seismic Toss",
        "id": 69,
        "jname": "ちきゅうなげ",
        "power": null,
        "pp": 20,
        "type": "Fighting"
    },
    {
        "accuracy": 90,
        "category": "变化",
        "cname": "寄生种子",
        "ename": "Leech Seed",
        "id": 73,
        "jname": "やどりぎのタネ",
        "power": null,
        "pp": 10,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "生长",
        "ename": "Growth",
        "id": 74,
        "jname": "せいちょう",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": 75,
        "category": "变化",
        "cname": "毒粉末",
        "ename": "Poison Powder",
        "id": 77,
        "jname": "どくのこな",
        "power": null,
        "pp": 35,
        "type": "Poison"
    },
    {
        "accuracy": 75,
        "category": "变化",
        "cname": "麻痹粉",
        "ename": "Stun Spore",
        "id": 78,
        "jname": "しびれごな",
        "power": null,
        "pp": 30,
        "type": "Grass"
    },
    {
        "accuracy": 75,
        "category": "变化",
        "cname": "睡眠粉",
        "ename": "Sleep Powder",
        "id": 79,
        "jname": "ねむりごな",
        "power": null,
        "pp": 15,
        "type": "Grass"
    },
    {
        "accuracy": 95,
        "category": "变化",
        "cname": "吐丝",
        "ename": "String Shot",
        "id": 81,
        "jname": "いとをはく",
        "power": null,
        "pp": 40,
        "type": "Bug"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "龙之怒",
        "ename": "Dragon Rage",
        "id": 82,
        "jname": "りゅうのいかり",
        "power": null,
        "pp": 10,
        "type": "Dragon"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "电磁波",
        "ename": "Thunder Wave",
        "id": 86,
        "jname": "でんじは",
        "power": null,
        "pp": 20,
        "tm": 73,
        "type": "Electric"
    },
    {
        "accuracy": 30,
        "category": "物理",
        "cname": "地裂",
        "ename": "Fissure",
        "id": 90,
        "jname": "じわれ",
        "power": null,
        "pp": 5,
        "type": "Ground"
    },
    {
        "accuracy": 90,
        "category": "变化",
        "cname": "猛毒素",
        "ename": "Toxic",
        "id": 92,
        "jname": "どくどく",
        "power": null,
        "pp": 10,
        "tm": 6,
        "type": "Poison"
    },
    {
        "accuracy": 60,
        "category": "变化",
        "cname": "催眠术",
        "ename": "Hypnosis",
        "id": 95,
        "jname": "さいみんじゅつ",
        "power": null,
        "pp": 20,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "瑜伽姿势",
        "ename": "Meditate",
        "id": 96,
        "jname": "ヨガのポーズ",
        "power": null,
        "pp": 40,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "高速移动",
        "ename": "Agility",
        "id": 97,
        "jname": "こうそくいどう",
        "power": null,
        "pp": 30,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "瞬间移动",
        "ename": "Teleport",
        "id": 100,
        "jname": "テレポート",
        "power": null,
        "pp": 20,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "黑夜诅咒",
        "ename": "Night Shade",
        "id": 101,
        "jname": "ナイトヘッド",
        "power": null,
        "pp": 15,
        "type": "Ghost"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "模仿",
        "ename": "Mimic",
        "id": 102,
        "jname": "ものまね",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 85,
        "category": "变化",
        "cname": "噪音",
        "ename": "Screech",
        "id": 103,
        "jname": "いやなおと",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "影子分身",
        "ename": "Double Team",
        "id": 104,
        "jname": "かげぶんしん",
        "power": null,
        "pp": 15,
        "tm": 32,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "自我复原",
        "ename": "Recover",
        "id": 105,
        "jname": "じこさいせい",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "硬梆梆",
        "ename": "Harden",
        "id": 106,
        "jname": "かたくなる",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "缩小",
        "ename": "Minimize",
        "id": 107,
        "jname": "ちいさくなる",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "烟幕",
        "ename": "Smokescreen",
        "id": 108,
        "jname": "えんまく",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "奇异光线",
        "ename": "Confuse Ray",
        "id": 109,
        "jname": "あやしいひかり",
        "power": null,
        "pp": 10,
        "type": "Ghost"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "缩壳",
        "ename": "Withdraw",
        "id": 110,
        "jname": "からにこもる",
        "power": null,
        "pp": 40,
        "type": "Water"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "防卫卷",
        "ename": "Defense Curl",
        "id": 111,
        "jname": "まるくなる",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "障碍",
        "ename": "Barrier",
        "id": 112,
        "jname": "バリアー",
        "power": null,
        "pp": 30,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "光墙",
        "ename": "Light Screen",
        "id": 113,
        "jname": "ひかりのかべ",
        "power": null,
        "pp": 30,
        "tm": 16,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "黑雾",
        "ename": "Haze",
        "id": 114,
        "jname": "くろいきり",
        "power": null,
        "pp": 30,
        "type": "Ice"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "减半反射",
        "ename": "Reflect",
        "id": 115,
        "jname": "リフレクター",
        "power": null,
        "pp": 20,
        "tm": 33,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "集气",
        "ename": "Focus Energy",
        "id": 116,
        "jname": "きあいだめ",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "物理",
        "cname": "忍忍",
        "ename": "Bide",
        "id": 117,
        "jname": "がまん",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "挥指功",
        "ename": "Metronome",
        "id": 118,
        "jname": "ゆびをふる",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "学舌术",
        "ename": "Mirror Move",
        "id": 119,
        "jname": "オウムがえし",
        "power": null,
        "pp": 20,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "瞬间失忆",
        "ename": "Amnesia",
        "id": 133,
        "jname": "ドわすれ",
        "power": null,
        "pp": 20,
        "type": "Psychic"
    },
    {
        "accuracy": 80,
        "category": "变化",
        "cname": "折弯汤匙",
        "ename": "Kinesis",
        "id": 134,
        "jname": "スプーンまげ",
        "power": null,
        "pp": 15,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "生蛋",
        "ename": "Soft-Boiled",
        "id": 135,
        "jname": "タマゴうみ",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "大蛇瞪眼",
        "ename": "Glare",
        "id": 137,
        "jname": "へびにらみ",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 90,
        "category": "变化",
        "cname": "毒瓦斯",
        "ename": "Poison Gas",
        "id": 139,
        "jname": "どくガス",
        "power": null,
        "pp": 40,
        "type": "Poison"
    },
    {
        "accuracy": 75,
        "category": "变化",
        "cname": "恶魔之吻",
        "ename": "Lovely Kiss",
        "id": 142,
        "jname": "あくまのキッス",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "变身",
        "ename": "Transform",
        "id": 144,
        "jname": "へんしん",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "蘑菇孢子",
        "ename": "Spore",
        "id": 147,
        "jname": "キノコのほうし",
        "power": null,
        "pp": 15,
        "type": "Grass"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "闪光",
        "ename": "Flash",
        "id": 148,
        "jname": "フラッシュ",
        "power": null,
        "pp": 20,
        "tm": 70,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "幻象波",
        "ename": "Psywave",
        "id": 149,
        "jname": "サイコウェーブ",
        "power": null,
        "pp": 15,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "水溅跃",
        "ename": "Splash",
        "id": 150,
        "jname": "はねる",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "溶化",
        "ename": "Acid Armor",
        "id": 151,
        "jname": "とける",
        "power": null,
        "pp": 20,
        "type": "Poison"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "睡觉",
        "ename": "Rest",
        "id": 156,
        "jname": "ねむる",
        "power": null,
        "pp": 10,
        "tm": 44,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "棱角",
        "ename": "Sharpen",
        "id": 159,
        "jname": "かくばる",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "变性",
        "ename": "Conversion",
        "id": 160,
        "jname": "テクスチャー",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 90,
        "category": "物理",
        "cname": "愤怒之牙",
        "ename": "Super Fang",
        "id": 162,
        "jname": "いかりのまえば",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "替身",
        "ename": "Substitute",
        "id": 164,
        "jname": "みがわり",
        "power": null,
        "pp": 10,
        "tm": 90,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "写生",
        "ename": "Sketch",
        "id": 166,
        "jname": "スケッチ",
        "power": null,
        "pp": 1,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "蛛丝",
        "ename": "Spider Web",
        "id": 169,
        "jname": "クモのす",
        "power": null,
        "pp": 10,
        "type": "Bug"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "心眼",
        "ename": "Mind Reader",
        "id": 170,
        "jname": "こころのめ",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "恶梦",
        "ename": "Nightmare",
        "id": 171,
        "jname": "あくむ",
        "power": null,
        "pp": 15,
        "type": "Ghost"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "咒语",
        "ename": "Curse",
        "id": 174,
        "jname": "のろい",
        "power": null,
        "pp": null,
        "type": "Ghost"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "手足慌乱",
        "ename": "Flail",
        "id": 175,
        "jname": "じたばた",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "变性II",
        "ename": "Conversion 2",
        "id": 176,
        "jname": "テクスチャー２",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "棉孢子",
        "ename": "Cotton Spore",
        "id": 178,
        "jname": "わたほうし",
        "power": null,
        "pp": 40,
        "type": "Grass"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "起死回生",
        "ename": "Reversal",
        "id": 179,
        "jname": "きしかいせい",
        "power": null,
        "pp": 15,
        "type": "Fighting"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "痛恨",
        "ename": "Spite",
        "id": 180,
        "jname": "うらみ",
        "power": null,
        "pp": 10,
        "type": "Ghost"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "守住",
        "ename": "Protect",
        "id": 182,
        "jname": "まもる",
        "power": null,
        "pp": 10,
        "tm": 17,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "鬼脸",
        "ename": "Scary Face",
        "id": 184,
        "jname": "こわいかお",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 75,
        "category": "变化",
        "cname": "天使之吻",
        "ename": "Sweet Kiss",
        "id": 186,
        "jname": "てんしのキッス",
        "power": null,
        "pp": 10,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "肚子大鼓",
        "ename": "Belly Drum",
        "id": 187,
        "jname": "はらだいこ",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "满地星",
        "ename": "Spikes",
        "id": 191,
        "jname": "まきびし",
        "power": null,
        "pp": 20,
        "type": "Ground"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "看破",
        "ename": "Foresight",
        "id": 193,
        "jname": "みやぶる",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "同命",
        "ename": "Destiny Bond",
        "id": 194,
        "jname": "みちづれ",
        "power": null,
        "pp": 5,
        "type": "Ghost"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "灭亡之歌",
        "ename": "Perish Song",
        "id": 195,
        "jname": "ほろびのうた",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "先决",
        "ename": "Detect",
        "id": 197,
        "jname": "みきり",
        "power": null,
        "pp": 5,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "锁定",
        "ename": "Lock-On",
        "id": 199,
        "jname": "ロックオン",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "沙雹",
        "ename": "Sandstorm",
        "id": 201,
        "jname": "すなあらし",
        "power": null,
        "pp": 10,
        "tm": 37,
        "type": "Rock"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "忍耐",
        "ename": "Endure",
        "id": 203,
        "jname": "こらえる",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "撒娇",
        "ename": "Charm",
        "id": 204,
        "jname": "あまえる",
        "power": null,
        "pp": 20,
        "type": "Fairy"
    },
    {
        "accuracy": 90,
        "category": "变化",
        "cname": "装腔作势",
        "ename": "Swagger",
        "id": 207,
        "jname": "いばる",
        "power": null,
        "pp": 15,
        "tm": 87,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "饮奶",
        "ename": "Milk Drink",
        "id": 208,
        "jname": "ミルクのみ",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "黑色眼光",
        "ename": "Mean Look",
        "id": 212,
        "jname": "くろいまなざし",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "迷人",
        "ename": "Attract",
        "id": 213,
        "jname": "メロメロ",
        "power": null,
        "pp": 15,
        "tm": 45,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "梦话",
        "ename": "Sleep Talk",
        "id": 214,
        "jname": "ねごと",
        "power": null,
        "pp": 10,
        "tm": 88,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "治愈铃声",
        "ename": "Heal Bell",
        "id": 215,
        "jname": "いやしのすず",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "报恩",
        "ename": "Return",
        "id": 216,
        "jname": "おんがえし",
        "power": null,
        "pp": 20,
        "tm": 27,
        "type": "Normal"
    },
    {
        "accuracy": 90,
        "category": "物理",
        "cname": "礼物",
        "ename": "Present",
        "id": 217,
        "jname": "プレゼント",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "牵连",
        "ename": "Frustration",
        "id": 218,
        "jname": "やつあたり",
        "power": null,
        "pp": 20,
        "tm": 21,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "神秘护身",
        "ename": "Safeguard",
        "id": 219,
        "jname": "しんぴのまもり",
        "power": null,
        "pp": 25,
        "tm": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "分享痛楚",
        "ename": "Pain Split",
        "id": 220,
        "jname": "いたみわけ",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "震级",
        "ename": "Magnitude",
        "id": 222,
        "jname": "マグニチュード",
        "power": null,
        "pp": 30,
        "type": "Ground"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "接棒",
        "ename": "Baton Pass",
        "id": 226,
        "jname": "バトンタッチ",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "再来一次",
        "ename": "Encore",
        "id": 227,
        "jname": "アンコール",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "甜气",
        "ename": "Sweet Scent",
        "id": 230,
        "jname": "あまいかおり",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "晨光",
        "ename": "Morning Sun",
        "id": 234,
        "jname": "あさのひざし",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "光学合成",
        "ename": "Synthesis",
        "id": 235,
        "jname": "こうごうせい",
        "power": null,
        "pp": 5,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "月光",
        "ename": "Moonlight",
        "id": 236,
        "jname": "つきのひかり",
        "power": null,
        "pp": 5,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "乞雨",
        "ename": "Rain Dance",
        "id": 240,
        "jname": "あまごい",
        "power": null,
        "pp": 5,
        "tm": 18,
        "type": "Water"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "大晴天",
        "ename": "Sunny Day",
        "id": 241,
        "jname": "にほんばれ",
        "power": null,
        "pp": 5,
        "tm": 11,
        "type": "Fire"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "表面涂层",
        "ename": "Mirror Coat",
        "id": 243,
        "jname": "ミラーコート",
        "power": null,
        "pp": 20,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "自我暗示",
        "ename": "Psych Up",
        "id": 244,
        "jname": "じこあんじ",
        "power": null,
        "pp": 10,
        "tm": 77,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "痛打一气",
        "ename": "Beat Up",
        "id": 251,
        "jname": "ふくろだたき",
        "power": null,
        "pp": 10,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "储存",
        "ename": "Stockpile",
        "id": 254,
        "jname": "たくわえる",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "喷出",
        "ename": "Spit Up",
        "id": 255,
        "jname": "はきだす",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "吞下",
        "ename": "Swallow",
        "id": 256,
        "jname": "のみこむ",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "冰雹",
        "ename": "Hail",
        "id": 258,
        "jname": "あられ",
        "power": null,
        "pp": 10,
        "tm": 7,
        "type": "Ice"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "假指控",
        "ename": "Torment",
        "id": 259,
        "jname": "いちゃもん",
        "power": null,
        "pp": 15,
        "tm": 41,
        "type": "Dark"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "煽惑",
        "ename": "Flatter",
        "id": 260,
        "jname": "おだてる",
        "power": null,
        "pp": 15,
        "type": "Dark"
    },
    {
        "accuracy": 85,
        "category": "变化",
        "cname": "鬼火",
        "ename": "Will-O-Wisp",
        "id": 261,
        "jname": "おにび",
        "power": null,
        "pp": 15,
        "tm": 61,
        "type": "Fire"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "临别礼物",
        "ename": "Memento",
        "id": 262,
        "jname": "おきみやげ",
        "power": null,
        "pp": 10,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "跟我来",
        "ename": "Follow Me",
        "id": 266,
        "jname": "このゆびとまれ",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "自然能力",
        "ename": "Nature Power",
        "id": 267,
        "jname": "しぜんのちから",
        "power": null,
        "pp": 20,
        "tm": 96,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "充电",
        "ename": "Charge",
        "id": 268,
        "jname": "じゅうでん",
        "power": null,
        "pp": 20,
        "type": "Electric"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "挑拨",
        "ename": "Taunt",
        "id": 269,
        "jname": "ちょうはつ",
        "power": null,
        "pp": 20,
        "tm": 12,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "帮助",
        "ename": "Helping Hand",
        "id": 270,
        "jname": "てだすけ",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "骗术",
        "ename": "Trick",
        "id": 271,
        "jname": "トリック",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "角色扮演",
        "ename": "Role Play",
        "id": 272,
        "jname": "なりきり",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "祈求",
        "ename": "Wish",
        "id": 273,
        "jname": "ねがいごと",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "协助",
        "ename": "Assist",
        "id": 274,
        "jname": "ねこのて",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "根深蒂固",
        "ename": "Ingrain",
        "id": 275,
        "jname": "ねをはる",
        "power": null,
        "pp": 20,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "魔术外衣",
        "ename": "Magic Coat",
        "id": 277,
        "jname": "マジックコート",
        "power": null,
        "pp": 15,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "回收",
        "ename": "Recycle",
        "id": 278,
        "jname": "リサイクル",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "哈欠",
        "ename": "Yawn",
        "id": 281,
        "jname": "あくび",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "强攻",
        "ename": "Endeavor",
        "id": 283,
        "jname": "がむしゃら",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "交换绝招",
        "ename": "Skill Swap",
        "id": 285,
        "jname": "スキルスワップ",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "封印",
        "ename": "Imprison",
        "id": 286,
        "jname": "ふういん",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "清新",
        "ename": "Refresh",
        "id": 287,
        "jname": "リフレッシュ",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "怨恨",
        "ename": "Grudge",
        "id": 288,
        "jname": "おんねん",
        "power": null,
        "pp": 5,
        "type": "Ghost"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "抢夺",
        "ename": "Snatch",
        "id": 289,
        "jname": "よこどり",
        "power": null,
        "pp": 10,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "保护色",
        "ename": "Camouflage",
        "id": 293,
        "jname": "ほごしょく",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "萤火",
        "ename": "Tail Glow",
        "id": 294,
        "jname": "ほたるび",
        "power": null,
        "pp": 20,
        "type": "Bug"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "羽毛舞",
        "ename": "Feather Dance",
        "id": 297,
        "jname": "フェザーダンス",
        "power": null,
        "pp": 15,
        "type": "Fighting"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "摇晃舞",
        "ename": "Teeter Dance",
        "id": 298,
        "jname": "フラフラダンス",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "玩泥巴",
        "ename": "Mud Sport",
        "id": 300,
        "jname": "どろあそび",
        "power": null,
        "pp": 15,
        "type": "Ground"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "懒惰",
        "ename": "Slack Off",
        "id": 303,
        "jname": "なまける",
        "power": null,
        "pp": 10,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "芳香治疗",
        "ename": "Aromatherapy",
        "id": 312,
        "jname": "アロマセラピー",
        "power": null,
        "pp": 5,
        "type": "Grass"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "假哭",
        "ename": "Fake Tears",
        "id": 313,
        "jname": "うそなき",
        "power": null,
        "pp": 20,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "气味侦测",
        "ename": "Odor Sleuth",
        "id": 316,
        "jname": "かぎわける",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": 85,
        "category": "变化",
        "cname": "金属音",
        "ename": "Metal Sound",
        "id": 319,
        "jname": "きんぞくおん",
        "power": null,
        "pp": 40,
        "type": "Steel"
    },
    {
        "accuracy": 55,
        "category": "变化",
        "cname": "草笛魔音",
        "ename": "Grass Whistle",
        "id": 320,
        "jname": "くさぶえ",
        "power": null,
        "pp": 15,
        "type": "Grass"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "搔痒",
        "ename": "Tickle",
        "id": 321,
        "jname": "くすぐる",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "无限能量",
        "ename": "Cosmic Power",
        "id": 322,
        "jname": "コスモパワー",
        "power": null,
        "pp": 20,
        "type": "Psychic"
    },
    {
        "accuracy": 30,
        "category": "特殊",
        "cname": "绝对零度",
        "ename": "Sheer Cold",
        "id": 329,
        "jname": "ぜったいれいど",
        "power": null,
        "pp": 5,
        "type": "Ice"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "铁壁",
        "ename": "Iron Defense",
        "id": 334,
        "jname": "てっぺき",
        "power": null,
        "pp": 15,
        "type": "Steel"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "挡路",
        "ename": "Block",
        "id": 335,
        "jname": "とおせんぼう",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "长嚎",
        "ename": "Howl",
        "id": 336,
        "jname": "とおぼえ",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "健美",
        "ename": "Bulk Up",
        "id": 339,
        "jname": "ビルドアップ",
        "power": null,
        "pp": 20,
        "tm": 8,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "水之游",
        "ename": "Water Sport",
        "id": 346,
        "jname": "みずあそび",
        "power": null,
        "pp": 15,
        "type": "Water"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "冥想",
        "ename": "Calm Mind",
        "id": 347,
        "jname": "めいそう",
        "power": null,
        "pp": 20,
        "tm": 4,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "龙之舞",
        "ename": "Dragon Dance",
        "id": 349,
        "jname": "りゅうのまい",
        "power": null,
        "pp": 20,
        "type": "Dragon"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "歇息",
        "ename": "Roost",
        "id": 355,
        "jname": "はねやすめ",
        "power": null,
        "pp": 10,
        "tm": 19,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "重力",
        "ename": "Gravity",
        "id": 356,
        "jname": "じゅうりょく",
        "power": null,
        "pp": 5,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "奇迹眼",
        "ename": "Miracle Eye",
        "id": 357,
        "jname": "ミラクルアイ",
        "power": null,
        "pp": 40,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "回转球",
        "ename": "Gyro Ball",
        "id": 360,
        "jname": "ジャイロボール",
        "power": null,
        "pp": 5,
        "tm": 74,
        "type": "Steel"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "治愈愿望",
        "ename": "Healing Wish",
        "id": 361,
        "jname": "いやしのねがい",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "自然之恩",
        "ename": "Natural Gift",
        "id": 363,
        "jname": "しぜんのめぐみ",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "顺风",
        "ename": "Tailwind",
        "id": 366,
        "jname": "おいかぜ",
        "power": null,
        "pp": 30,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "点穴",
        "ename": "Acupressure",
        "id": 367,
        "jname": "つぼをつく",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "合金爆裂",
        "ename": "Metal Burst",
        "id": 368,
        "jname": "メタルバースト",
        "power": null,
        "pp": 10,
        "type": "Steel"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "征收",
        "ename": "Embargo",
        "id": 373,
        "jname": "さしおさえ",
        "power": null,
        "pp": 15,
        "tm": 63,
        "type": "Dark"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "投掷",
        "ename": "Fling",
        "id": 374,
        "jname": "なげつける",
        "power": null,
        "pp": 10,
        "tm": 56,
        "type": "Dark"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "幻象转移",
        "ename": "Psycho Shift",
        "id": 375,
        "jname": "サイコシフト",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "特殊",
        "cname": "王牌",
        "ename": "Trump Card",
        "id": 376,
        "jname": "きりふだ",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "回复阻挡",
        "ename": "Heal Block",
        "id": 377,
        "jname": "かいふくふうじ",
        "power": null,
        "pp": 15,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "拧干",
        "ename": "Wring Out",
        "id": 378,
        "jname": "しぼりとる",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "能量骗术",
        "ename": "Power Trick",
        "id": 379,
        "jname": "パワートリック",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "胃液",
        "ename": "Gastro Acid",
        "id": 380,
        "jname": "いえき",
        "power": null,
        "pp": 10,
        "type": "Poison"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "幸运咒语",
        "ename": "Lucky Chant",
        "id": 381,
        "jname": "おまじない",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "先抢先赢",
        "ename": "Me First",
        "id": 382,
        "jname": "さきどり",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "仿造",
        "ename": "Copycat",
        "id": 383,
        "jname": "まねっこ",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "力量交换",
        "ename": "Power Swap",
        "id": 384,
        "jname": "パワースワップ",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "防御交换",
        "ename": "Guard Swap",
        "id": 385,
        "jname": "ガードスワップ",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "惩罚",
        "ename": "Punishment",
        "id": 386,
        "jname": "おしおき",
        "power": null,
        "pp": 5,
        "type": "Dark"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "烦恼种子",
        "ename": "Worry Seed",
        "id": 388,
        "jname": "なやみのタネ",
        "power": null,
        "pp": 10,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "毒尖钉",
        "ename": "Toxic Spikes",
        "id": 390,
        "jname": "どくびし",
        "power": null,
        "pp": 20,
        "type": "Poison"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "交换意志",
        "ename": "Heart Swap",
        "id": 391,
        "jname": "ハートスワップ",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "水柱圈",
        "ename": "Aqua Ring",
        "id": 392,
        "jname": "アクアリング",
        "power": null,
        "pp": 20,
        "type": "Water"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "电磁浮游",
        "ename": "Magnet Rise",
        "id": 393,
        "jname": "でんじふゆう",
        "power": null,
        "pp": 10,
        "type": "Electric"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "磨光岩石",
        "ename": "Rock Polish",
        "id": 397,
        "jname": "ロックカット",
        "power": null,
        "pp": 20,
        "tm": 69,
        "type": "Rock"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "掉包",
        "ename": "Switcheroo",
        "id": 415,
        "jname": "すりかえ",
        "power": null,
        "pp": 10,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "诡计",
        "ename": "Nasty Plot",
        "id": 417,
        "jname": "わるだくみ",
        "power": null,
        "pp": 20,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "清除浓雾",
        "ename": "Defog",
        "id": 432,
        "jname": "きりばらい",
        "power": null,
        "pp": 15,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "骗术空间",
        "ename": "Trick Room",
        "id": 433,
        "jname": "トリックルーム",
        "power": null,
        "pp": 5,
        "tm": 92,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "诱惑",
        "ename": "Captivate",
        "id": 445,
        "jname": "ゆうわく",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "隐形岩",
        "ename": "Stealth Rock",
        "id": 446,
        "jname": "ステルスロック",
        "power": null,
        "pp": 20,
        "type": "Rock"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "打草结",
        "ename": "Grass Knot",
        "id": 447,
        "jname": "くさむすび",
        "power": null,
        "pp": 20,
        "tm": 86,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "防御指令",
        "ename": "Defend Order",
        "id": 455,
        "jname": "ぼうぎょしれい",
        "power": null,
        "pp": 10,
        "type": "Bug"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "回复指令",
        "ename": "Heal Order",
        "id": 456,
        "jname": "かいふくしれい",
        "power": null,
        "pp": 10,
        "type": "Bug"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "新月舞",
        "ename": "Lunar Dance",
        "id": 461,
        "jname": "みかづきのまい",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "捏碎",
        "ename": "Crush Grip",
        "id": 462,
        "jname": "にぎりつぶす",
        "power": null,
        "pp": 5,
        "type": "Normal"
    },
    {
        "accuracy": 80,
        "category": "变化",
        "cname": "黑洞",
        "ename": "Dark Void",
        "id": 464,
        "jname": "ダークホール",
        "power": null,
        "pp": 10,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "磨爪子",
        "ename": "Hone Claws",
        "id": 468,
        "jname": "つめとぎ",
        "power": null,
        "pp": 15,
        "tm": 1,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "全体防御",
        "ename": "Wide Guard",
        "id": 469,
        "jname": "ワイドガード",
        "power": null,
        "pp": 10,
        "type": "Rock"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "防御平分",
        "ename": "Guard Split",
        "id": 470,
        "jname": "ガードシェア",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "力量平分",
        "ename": "Power Split",
        "id": 471,
        "jname": "パワーシェア",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "奇妙空间",
        "ename": "Wonder Room",
        "id": 472,
        "jname": "ワンダールーム",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "体重减轻",
        "ename": "Autotomize",
        "id": 475,
        "jname": "ボディパージ",
        "power": null,
        "pp": 15,
        "type": "Steel"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "愤怒之粉",
        "ename": "Rage Powder",
        "id": 476,
        "jname": "いかりのこな",
        "power": null,
        "pp": 20,
        "type": "Bug"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "心灵传动术",
        "ename": "Telekinesis",
        "id": 477,
        "jname": "テレキネシス",
        "power": null,
        "pp": 15,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "魔法空间",
        "ename": "Magic Room",
        "id": 478,
        "jname": "マジックルーム",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "蝶之舞",
        "ename": "Quiver Dance",
        "id": 483,
        "jname": "ちょうのまい",
        "power": null,
        "pp": 20,
        "type": "Bug"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "沉重轰炸",
        "ename": "Heavy Slam",
        "id": 484,
        "jname": "ヘビーボンバー",
        "power": null,
        "pp": 10,
        "type": "Steel"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "电球",
        "ename": "Electro Ball",
        "id": 486,
        "jname": "エレキボール",
        "power": null,
        "pp": 10,
        "type": "Electric"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "浸水",
        "ename": "Soak",
        "id": 487,
        "jname": "みずびたし",
        "power": null,
        "pp": 20,
        "type": "Water"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "盘卷",
        "ename": "Coil",
        "id": 489,
        "jname": "とぐろをまく",
        "power": null,
        "pp": 20,
        "type": "Poison"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "单纯光线",
        "ename": "Simple Beam",
        "id": 493,
        "jname": "シンプルビーム",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "变为同伴",
        "ename": "Entrainment",
        "id": 494,
        "jname": "なかまづくり",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "你先请",
        "ename": "After You",
        "id": 495,
        "jname": "おさきにどうぞ",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "先制防御",
        "ename": "Quick Guard",
        "id": 501,
        "jname": "ファストガード",
        "power": null,
        "pp": 15,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "位置交换",
        "ename": "Ally Switch",
        "id": 502,
        "jname": "サイドチェンジ",
        "power": null,
        "pp": 15,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "破壳",
        "ename": "Shell Smash",
        "id": 504,
        "jname": "からをやぶる",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "治愈波动",
        "ename": "Heal Pulse",
        "id": 505,
        "jname": "いやしのはどう",
        "power": null,
        "pp": 10,
        "type": "Psychic"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "交换齿轮",
        "ename": "Shift Gear",
        "id": 508,
        "jname": "ギアチェンジ",
        "power": null,
        "pp": 10,
        "type": "Steel"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "延后",
        "ename": "Quash",
        "id": 511,
        "jname": "さきおくり",
        "power": null,
        "pp": 15,
        "tm": 60,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "镜子系",
        "ename": "Reflect Type",
        "id": 513,
        "jname": "ミラータイプ",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "特殊",
        "cname": "赌命",
        "ename": "Final Gambit",
        "id": 515,
        "jname": "いのちがけ",
        "power": null,
        "pp": 5,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "礼物传递",
        "ename": "Bestow",
        "id": 516,
        "jname": "ギフトパス",
        "power": null,
        "pp": 15,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "自我激励",
        "ename": "Work Up",
        "id": 526,
        "jname": "ふるいたてる",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "高温捣击",
        "ename": "Heat Crash",
        "id": 535,
        "jname": "ヒートスタンプ",
        "power": null,
        "pp": 10,
        "type": "Fire"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "棉花防御",
        "ename": "Cotton Guard",
        "id": 538,
        "jname": "コットンガード",
        "power": null,
        "pp": 10,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "垫返",
        "ename": "Mat Block",
        "id": 561,
        "jname": "たたみがえし",
        "power": null,
        "pp": 15,
        "type": "Fighting"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "耕地",
        "ename": "Rototiller",
        "id": 563,
        "jname": "たがやす",
        "power": null,
        "pp": 10,
        "type": "Ground"
    },
    {
        "accuracy": null,
        "category": "物理",
        "cname": "粘网",
        "ename": "Sticky Web",
        "id": 564,
        "jname": "ねばねばネット",
        "power": null,
        "pp": 20,
        "type": "Bug"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "万圣夜狂欢",
        "ename": "Trick-or-Treat",
        "id": 567,
        "jname": "ハロウィン",
        "power": null,
        "pp": 20,
        "type": "Ghost"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "战吼",
        "ename": "Noble Roar",
        "id": 568,
        "jname": "おたけび",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": 25,
        "category": "变化",
        "cname": "电浆阵雨",
        "ename": "Ion Deluge",
        "id": 569,
        "jname": "プラズマシャワー",
        "power": null,
        "pp": 25,
        "type": "Electric"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "森林诅咒",
        "ename": "Forest's Curse",
        "id": 571,
        "jname": "もりののろい",
        "power": null,
        "pp": 20,
        "type": "Grass"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "放狠话",
        "ename": "Parting Shot",
        "id": 575,
        "jname": "すてゼリフ",
        "power": null,
        "pp": 20,
        "type": "Dark"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "翻倒",
        "ename": "Topsy-Turvy",
        "id": 576,
        "jname": "ひっくりかえす",
        "power": null,
        "pp": 20,
        "type": "Dark"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "狡猾防御",
        "ename": "Crafty Shield",
        "id": 578,
        "jname": "トリックガード",
        "power": null,
        "pp": 10,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "鲜花防御",
        "ename": "Flower Shield",
        "id": 579,
        "jname": "フラワーガード",
        "power": null,
        "pp": 10,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "草原场地",
        "ename": "Grassy Terrain",
        "id": 580,
        "jname": "グラスフィールド",
        "power": null,
        "pp": 10,
        "type": "Grass"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "薄雾场地",
        "ename": "Misty Terrain",
        "id": 581,
        "jname": "ミストフィールド",
        "power": null,
        "pp": 10,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "送电",
        "ename": "Electrify",
        "id": 582,
        "jname": "そうでん",
        "power": null,
        "pp": 20,
        "type": "Electric"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "妖精之锁",
        "ename": "Fairy Lock",
        "id": 587,
        "jname": "フェアリーロック",
        "power": null,
        "pp": 10,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "王者之盾",
        "ename": "King's Shield",
        "id": 588,
        "jname": "キングシールド",
        "power": null,
        "pp": 10,
        "type": "Steel"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "做朋友",
        "ename": "Play Nice",
        "id": 589,
        "jname": "なかよくする",
        "power": null,
        "pp": 20,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "私话",
        "ename": "Confide",
        "id": 590,
        "jname": "ないしょばなし",
        "power": null,
        "pp": 20,
        "tm": 100,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "刺针防御",
        "ename": "Spiky Shield",
        "id": 596,
        "jname": "ニードルガード",
        "power": null,
        "pp": 10,
        "type": "Grass"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "芳香薄雾",
        "ename": "Aromatic Mist",
        "id": 597,
        "jname": "アロマミスト",
        "power": null,
        "pp": 20,
        "type": "Fairy"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "怪电波",
        "ename": "Eerie Impulse",
        "id": 598,
        "jname": "かいでんぱ",
        "power": null,
        "pp": 15,
        "type": "Electric"
    },
    {
        "accuracy": 100,
        "category": "物理",
        "cname": "毒液陷阱",
        "ename": "Venom Drench",
        "id": 599,
        "jname": "ベノムトラップ",
        "power": null,
        "pp": 20,
        "type": "Poison"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "粉尘",
        "ename": "Powder",
        "id": 600,
        "jname": "ふんじん",
        "power": null,
        "pp": 20,
        "type": "Bug"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "大地控制",
        "ename": "Geomancy",
        "id": 601,
        "jname": "ジオコントロール",
        "power": null,
        "pp": 10,
        "type": "Fairy"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "磁场操作",
        "ename": "Magnetic Flux",
        "id": 602,
        "jname": "じばそうさ",
        "power": null,
        "pp": 20,
        "type": "Electric"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "快乐时间",
        "ename": "Happy Hour",
        "id": 603,
        "jname": "ハッピータイム",
        "power": null,
        "pp": 30,
        "type": "Normal"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "电气场地",
        "ename": "Electric Terrain",
        "id": 604,
        "jname": "エレキフィールド",
        "power": null,
        "pp": 10,
        "type": "Electric"
    },
    {
        "accuracy": null,
        "category": "变化",
        "cname": "庆祝",
        "ename": "Celebration",
        "id": 606,
        "jname": "おいわい",
        "power": null,
        "pp": 40,
        "type": "Normal"
    },
    {
        "accuracy": 100,
        "category": "变化",
        "cname": "圆滑目光",
        "ename": "Baby-Doll Eyes",
        "id": 608,
        "jname": "つぶらなひとみ",
        "power": null,
        "pp": 30,
        "type": "Fairy"
    }
]
